---
title: "Homework 5"
author: "Jiarui Fu"
date: "11/7/2019"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(broom)

```

## Problem 1

```{r}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))

replace_missing_values = function(x) {
  if (is.numeric(x)) {
    x=replace_na(x, mean(x, na.rm = TRUE))}
  else if (is.character(x)) {
    x=replace_na(x, "virginca")}
}

iris_new = map(iris_with_missing, replace_missing_values) 
as_tibble(iris_new)
```

## Problem 2
```{r}
files = list.files("data") 

tidy_data = tibble(filename = files) %>% 
  mutate(
    subject_info = map(filename, ~read_csv(file.path("./data", .)))
    ) %>% 
  unnest(cols = subject_info) %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    week_1:week_8,
    names_to = "week", 
    values_to = "observation"
  ) %>% 
  mutate_all(~gsub("week_", "", .)) %>% 
  separate(filename, into = "id_group", sep = ".csv") %>% 
  separate(id_group, into = c("arm", "subject_id"), sep = "_") %>% 
  mutate(arm = recode(arm, "con" = "control", "exp" = "experimental")) %>% 
  mutate(observation = as.numeric(observation))

tidy_data

ggplot(tidy_data, aes(x = week, y = observation, color = arm, 
                      group = interaction(arm, subject_id))) +
  geom_line()
```

## Problem 3
```{r}
sim_regression = function(n = 30, beta0 = 2, sigma_sq = 50, beta1) {
  
  sim_data = tibble(
    x = rnorm(n, mean = 0, sd = 1),
    y = beta0 + beta1 * x + rnorm(n, 0, sigma_sq)
  )
  
  ls_fit = lm(y ~ x, data = sim_data)
  summary = tidy(ls_fit) %>% 
    filter(term == "x")
  
  tibble(
  beta1_hat = summary$estimate,
  p_value = summary$p.value
  )
}

sim_results = 
  tibble(beta1 = c(0, 1, 2, 3, 4, 5, 6)) %>% 
  mutate(
    output_lists = map(.x = beta1, ~rerun(10000, sim_regression(beta1 = .x))),
    estimate_dfs = map(output_lists, bind_rows)) %>% 
  select(-output_lists) %>% 
  unnest(estimate_dfs)
sim_results

reject_proportion = 
  sim_results %>% 
  group_by(beta1) %>% 
  summarize(reject = length(which(p_value < 0.05)),
            total = n()) %>% 
  mutate(proportion = reject/total)

ggplot(reject_proportion, aes(x = beta1, y = proportion)) + 
  geom_point() +
  geom_line() +
  labs(y = "proportion of times the null was rejected",
       title = "The power of the test vs the effect size.")

average_estimate = 
  sim_results %>% 
  group_by(beta1) %>% 
  summarize(avg = mean(beta1_hat))

average_reject_null = 
  sim_results %>% 
  group_by(beta1) %>% 
  summarize(avg = mean(beta1_hat[p_value < 0.05]))

ggplot() +
  geom_point(average_estimate, mapping = aes(x = beta1, y = avg))+
  geom_line(average_estimate, mapping = aes(x = beta1, y = avg, color = "sample average")) +
  geom_point(average_reject_null, mapping = aes(x = beta1, y = avg)) +
  geom_line(average_reject_null, mapping = aes(x = beta1, y = avg, color = "samples for which the null was rejected")) +
  labs(y = "average estimate of beta1_hat",
       title = "The average estimate of beta1_hat vs the true value of beta1.")


  
  

  
```

